Repository gradle/cookbook, pull requests merged in 2024-10, with the labels that each got.

#6 Update mkdocs.yml
  mkdocs.yml
Labels: bug

#10 Add landing page, show contribution history
  .devcontainer/requirements.txt
  docs/android/README.md
  docs/chapters.md
  docs/index.md
  docs/preface.md
  mkdocs.yml
  overrides/home.html
Labels: enhancement

#11 Add issue templates
  .github/ISSUE_TEMPLATE/1-report-issue.yml
  .github/ISSUE_TEMPLATE/2-new-recipe.yml
  .github/ISSUE_TEMPLATE/3-new-chapter.yml
  .github/ISSUE_TEMPLATE/4-other.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore

#12 Add placeholders for Troubleshooting and Plugin Development chapters
  docs/chapters.md
  docs/plugin-development/README.md
  docs/troubleshooting/README.md
  mkdocs.yml
Labels: documentation

#13 Update Documentation: Enhance documentation of Gradle for Android
  docs/android/README.md
  docs/android/optimization.md
  docs/android/troubleshooting.md
Labels: documentation

#18 Add a section about writing plugins in Kotlin
  .gitignore
  docs/plugin-development/README.md
  docs/plugin-development/kotlin-plugins.md
Labels: documentation
